### ISSUE TITLE
Heat Level Calculations

### ISSUE THREAD

**Issue by ztlawton** [JamesBremner/workshoplocator#1]
The negative temperature values should all be increased by 2, as the heat value at a distance of 1 should be the full amount of heat produced by the module. For example, the Solar Module increases a Workshop's temperature by 10° at a distance of one Link, 8° at a distance of two Links, 6° at a distance of three Links, 4° at a distance of five Links, and 0° for any greater distance.

I'm also not sure how the code is handling negative values. For example, the Greenhouse Module produces +2° at a distance of 1 Link, so at a distance of 3 links its contribution should be +0° and not −2°; the Radiator Module produces −20° at a distance of 1 Link, so at a distance of 3 links its contribution should be −16° and not −24°.

**Comment by JamesBremner** [comment]
Do you want to implement this?

If you want me to do so, please assign the issue to me.

**Comment by ztlawton** [comment]
It looks like this still doesn't handle the Radiator's −20° heat contribution, but it should work for the other Modules!

**Comment by JamesBremner** [comment]
>  this still doesn't handle the Radiator's −20° heat contribution

Please explain.

https://github.com/JamesBremner/workshoplocator/blob/2f7dcabc77a9f472b43c06fbe5fb8a208a70e329/src/main.cpp#L153-L163

**Comment by ztlawton** [comment]
Oh, I missed that part. My bad, sorry.

**Comment by JamesBremner** [comment]
General note for future reference.  Never submit a test report that says nothing more than "It doesn't work"  Always explain.  "It doesn't work" all by itself is unhelpful and very annoying. It is a funny thing, but even now in 2023, many people still make this mistake - maybe one day they will teach how to write test reports in schools.

**Comment by JamesBremner** [comment]
I have assigned this back to you.  I suggest you do a test build on your fork and see if it works OK.  If your are happy with it, then close this issue.

**Comment by JamesBremner** [comment]
This has been assigned to you for 4 days.  Why are you keeping it open?
