### ISSUE TITLE
Central Grid Square Features

### ISSUE THREAD

**Issue by JamesBremner** [JamesBremner/workshoplocator#11]
There are some features to do with the central grid square

**Comment by ztlawton** [comment]
Summary of the central node's special features:
- Must be connected by Links to every node that contains either a Workshop or a Module. The length of the connecting path does not matter, and the connection can pass through other nodes that contain Workshops or Modules.
- Blocks heat propagation along Links.
- Blocks Module effect propagation along Links.
- Has no heat or other effect of its own.

**Comment by JamesBremner** [comment]
The only workshop that is likely to involve the central square is Electronics.  The simplest way to make this happen is to use a 1 1 5 0 0 mix

```
1 1 5 0 0  => Total Productivity: 553
    ..........
   .a..........
  ..gAg.........
 ...s.g..........
.sag.............
..B..............
.sag.............
.r.r.r.r.r.r.....
.cEcEcEcXcEc.....
.s.s.s.s.s.s.....
.t.t.t.t.t.t.....
.................
.................
.................
 ................
  ..............
   ............
```

I will add code to the electronics workshop layout to avoid this.

**Comment by JamesBremner** [comment]
```
1 1 5 0 0  => Total Productivity: 553
    ..........
   .a..........
  ..gAg.........
 ...s.g..........
.sag.............
..B..............
.sag.............
.r.r.r.r.r.r.r...
.cEcEcEcXcEcEc...
.s.s.s.s.s.s.s...
.t.t.t.t.t.t.t...
.................
.................
.................
 ................
  ..............
   ............
```

**Comment by JamesBremner** [comment]
v1.0.2

**Comment by JamesBremner** [comment]
Summary of the central node's special features:

- Must be connected by Links to every node that contains either a Workshop or a Module. The length of the connecting path does not matter, and the connection can pass through other nodes that contain Workshops or Modules.

This is moved to v2

---

- Blocks heat propagation along Links.
- Blocks Module effect propagation along Links.
- Has no heat or other effect of its own.

These issues are handled well in v1.  For example

```
Module Count: 42 ( max 48 )   Link Count: 48
2 2 4 0 0  => Total Productivity: 626
    ..........
   .a.a........
  ..gAgAg.......
 ...s.s..........
.sagas...........
..B.B............
.sagas...........
.r.r.r.r.r.r.....
.cEcEcEcXcEc.....
.s.s.s.s.s.s.....
.t.t.t.t.t.t.....
.................
.................
.................
 ................
  ..............
   ............
```

So, I think this issue can be closed
