### ISSUE TITLE
Ascii art displays module type character

### ISSUE THREAD

**Issue by JamesBremner** [JamesBremner/workshoplocator#15]
Currently this is done here

https://github.com/JamesBremner/workshoplocator/blob/22ef58ec1959eabc51f47fc891c14e22083846dd/src/cWorkshop.cpp#L296-L303

You will need to create a new cModule method, with a switch on the module type, and then replace line 301 with a call to your new method.

**Comment by JamesBremner** [comment]
It is very easy to get totally carried away with ascii art.  But, IMHO, it should only be used quick debugging checks.  If you want something pretty to look at, then the way to go is to use a GUI - which will give you much better displays with much simpler code.

**Comment by ztlawton** [comment]
Roger.

**Comment by JamesBremner** [comment]
I am still uncomfortable with placing insertAscii into the global namespace.  It is messy and ugly.

The correct OOD* solution is to have an AscciArt class that looks after all these messy details, which can then be removed from the classes that should not be concerned with them.

Would you mind if I took back this issue?  Once I have refactored the ascii art code into its own class, then I can assign it back to you to polish off the module display - which will then be a matter of modifying a method of the new class.

* OOD = Object Orientated Design

**Comment by JamesBremner** [comment]
I see you just accepted this.

OK, I will wait and when you are completed I will refactor everything, including your new code, into a new class.

Good coding!

**Comment by JamesBremner** [comment]
The ease of implementing this issue is exactly the same.  You labelled it accepted first, so you get first go.

**Comment by ztlawton** [comment]
Roger.

**Comment by JamesBremner** [comment]
How is this going?

**Comment by JamesBremner** [comment]
Hello?  You seem to be struggling with this one.  Can I help?  Or take it over?

**Comment by ztlawton** [comment]
Yeah, I'm kind of lost on how to do this.

**Comment by JamesBremner** [comment]
Do you understand my suggestion on how this could be done?  https://github.com/JamesBremner/workshoplocator/issues/15#issue-1675436553

How far have you got with implementing it?

**Comment by JamesBremner** [comment]
The first step would be to write the signature for the new cModule method and add it to the cModule declaration.

**Comment by ztlawton** [comment]
What do you mean by "write the signature for the new cModule method"?

**Comment by JamesBremner** [comment]
A method signature declares then name of the method, the parameters and the return type.

For example, here is the signature of the cWorkShop asciiArt() method

    void asciiArt( std::vector<std::vector<char>>& vgrid );

**Comment by ztlawton** [comment]
So I would copy that into the cModule method?

**Comment by JamesBremner** [comment]
That would work.

**Comment by JamesBremner** [comment]
You should copy that into the cModule _declaration_.

**Comment by ztlawton** [comment]
I do not.

**Comment by JamesBremner** [comment]
OK.

I must have misunderstood when you said something about being experienced with C++.  You will need to get a good book or extensive tutorial in basic C++ coding.

I will take it from here.

**Comment by ztlawton** [comment]
I did not say I was experienced with C++. I said I was self-taught with basic JavaScript and a bit of XML/HTML/CSS.

> [I don't have experience with C++](https://chat.stackoverflow.com/transcript/message/56218929#56218929)

> [I haven't taken formal, technical programming classes; my actual coding experience before now is pretty much entirely self-taught, using JavaScript and XML to automate mathematical constructions and calculations and a bit of HTML and CSS to make it look good.](https://github.com/ztlawton/workshoplocator/issues/1#issuecomment-1510606338_)

**Comment by ztlawton** [comment]
If you prefer other letters you can use whatever you want, but here are the letter codes I was thinking of using:

A (Agriculture)
B (Biotech)
E (Electronics)
N (Energy)
H (Heavy Industry)

r (Radiator)
s (Solar)
g (Greenhouse)
a (Artificial-G)
t (Stowage)
c (Recycling)

**Comment by JamesBremner** [comment]
Sorry, I misread that.  Of course, when you happily accepted C++ coding assignments I was confirmed in my misapprehension.

Thanks for the letter suggestions - I will use them.

**Comment by JamesBremner** [comment]
![image](https://user-images.githubusercontent.com/2046227/233789502-e005cdf6-7a59-442f-a338-93a2605bf7ca.png)

**Comment by ztlawton** [comment]
Looks good!
