### ISSUE TITLE
Implement workshop types

### ISSUE THREAD

**Issue by JamesBremner** [JamesBremner/workshoplocator#2]
The agriculture workshop is implemented

https://github.com/JamesBremner/workshoplocator/blob/11adce11426708fa39092cab4927813f78403aee/src/main.cpp#L55-L74

The other types need to be implemented.

**Comment by JamesBremner** [comment]
@ztlawton would you like to do this?

**Comment by ztlawton** [comment]
I think I can do it.

**Comment by JamesBremner** [comment]
The first step is to fork the repository - i.e. copy it to your account.

**Comment by ztlawton** [comment]
I added the other Workshop and Module types. How do I merge the changes?

**Comment by JamesBremner** [comment]
Please read my comments on your commit

**Comment by JamesBremner** [comment]
Since you are currently working on this issue, you should label it as "accepted".

**Comment by JamesBremner** [comment]
Remember to update text() for the new workshop types

https://github.com/JamesBremner/workshoplocator/blob/f7207849eac7aa77eafbe17905e9ebeba021a853/src/main.cpp#L186-L204

**Comment by ztlawton** [comment]
> Remember to update text() for the new workshop types

That is what I thought I was doing when I added the stringstream object. I didn't realize it was in a different section than where the other properties of the Workshops were defined.

**Comment by JamesBremner** [comment]
Please notice:

https://github.com/JamesBremner/workshoplocator/blob/4a69c6baa5cc9091bc982c49456a91f516e213f8/src/cWorkshop.cpp#L24-L26

**Comment by JamesBremner** [comment]
Hello?

I have the impression that you have the build problems all sorted out.  Well done, that is big.

I was hoping that your success meant that I would soon see a good pull request for some tested code implementing the other workshop types.  Are you still working on this?

**Comment by ztlawton** [comment]
I've spent hours trying to get my changes to work with no luck, but it just occurred to me to try building and running the code direct from your repository with no changes, and it crashes with no error message just like it's been doing for the last whole day. There must be something else wrong on my end, since I'm assuming it's not crashing with no error message on your end. How would you recommend diagnosing this problem?

**Comment by ztlawton** [comment]
The good news is that I did manage to get all the Workshop types implemented with no errors on running "starter" (building the EXE?). Hopefully that means it is viable code and the only problem is whatever is making the EXE crash even when built on your unaltered code.

**Comment by JamesBremner** [comment]
> I've spent hours trying to get my changes to work with no luck

Sorry about that.

Notice that finding a bug should never take hours. ( Fixing a bug once found is a different story )

So, how are you trying to find the cause of the crash?  The best way is to run it under the debugger, which will give you the line where the crash happened and the value of the variables.  Have you done this?

**Comment by JamesBremner** [comment]
Have you read https://github.com/ztlawton/workshoplocator/issues/1#issuecomment-1511706301 ?

**Comment by JamesBremner** [comment]
> running the code direct from your repository with no changes, and it crashes with no error message

My repo has no code for any workshops other than agriculture.  So if you try running it with other workshops in the mix it will fail.  You should get an unrecognized workshop exception.

```
Input Workshop Mix
Enter number of each workshop type in order
Agriculture Biotech Electronics Energy HeavyIndustry
0 1 1 1 1
terminate called after throwing an instance of 'std::runtime_error'
  what():  cWorkshop::cWorkshop unrecognized type
```

**Comment by JamesBremner** [comment]
I am breaking for lunch now.  If you haven't tracked down the bug ( the cause, not the fix :-) when I get back, I will take a look at it for you.

**Comment by ztlawton** [comment]
The window closes with no error message when I enter "12 0 0 0 0" for the Workshop mix. If I enter a mix with other Workshop types, I get the error message you say I should:
```
terminate called after throwing an instance of 'std::runtime_error'
  what():  cWorkshop::cWorkshop unrecognized type
```

**Comment by ztlawton** [comment]
Forgot to respond to your other question, I did use the debugger and it seems to run fine there. It's only the EXE that crashes. That's why I haven't figured it out.

**Comment by JamesBremner** [comment]
It runs successfully when I use that input

```
C:\Users\James\code\workshoplocator\bin>workshoplocator.exe
Input Workshop Mix
Enter number of each workshop type in order
Agriculture Biotech Electronics Energy HeavyIndustry
12 0 0 0 0

Layout
Agriculture workshop: location: 2 4 temp: 40 productivity: 52
        GreenHouse module: location: 1 4
        GreenHouse module: location: 3 4
        Solar module: location: 2 5
        ArtificialG module: location: 2 3
Agriculture workshop: location: 4 4 temp: 40 productivity: 40
        ArtificialG module: location: 2 3
        GreenHouse module: location: 5 4
        Solar module: location: 4 5
        ArtificialG module: location: 4 3
Agriculture workshop: location: 6 4 temp: 40 productivity: 40

 ... and so on
```

> The window closes with no error message

This sounds very odd.  What exactly do you mean?  Even if the application crashes the terminal window will remain open.  Are you running from a cmd terminal or from the IDE terminal? 

Are you certain are building the tip of the main branch.  It should look like this

![image](https://user-images.githubusercontent.com/2046227/232855020-b9c9ca4b-7369-4b63-94f3-02928bb6c286.png)

**Comment by JamesBremner** [comment]
>  It's only the EXE that crashes.

Very surprising!  Have you placed a breakpoint in the main function and stepped though it?

**Comment by JamesBremner** [comment]
> It's only the EXE that crashes.

Actually this makes no sense.  If you run from a terminal command or from the debugger, you are running the same .exe in both cases.

I suppose you mean that running under the debugger is successful, but omething bad happens when you run from a terminal command.  What terminal are you using.  Please post the command you use, something like this

C:\Users\James\code\workshoplocator\bin>workshoplocator.exe

**Comment by JamesBremner** [comment]
> The window closes with no error message

I wonder .... could it possibly be that you are trying to run a console application by double clicking on the executable filename in the windows file explorer?

If so, then yes the window pops up and then closes when the application finishes.  Please confirm that you are running from a terminal window.

**Comment by JamesBremner** [comment]
How to run a console application:

- Type "cmd" in the search bar

![image](https://user-images.githubusercontent.com/2046227/232858164-4de6fe30-fa06-49f5-9fd1-99d0c9b0cf43.png)

- In the terminal window cd to the bin folder containing the executable
- Type the executable name

```
C:\Users\James\code>cd workshoplocator\bin

C:\Users\James\code\workshoplocator\bin>workshopLocator.exe
Input Workshop Mix
Enter number of each workshop type in order
Agriculture Biotech Electronics Energy HeavyIndustry
```

**Comment by ztlawton** [comment]
😑 I have been double-clicking the EXE file to run it. I'll get back to you with the other Workshop types.

**Comment by JamesBremner** [comment]
Always run applications of any kind ( that is, console OR GUI ) from a terminal window.  It is useless to run console applications by double clicking the executable.  For GUIs you lose valuable error messages that will help with debugging.  The double clicking method is only for people who are intimidated by terminals - you shouldn't be using it.

**Comment by JamesBremner** [comment]
Bravo!
