### ISSUE TITLE
Workshop mix input

### ISSUE THREAD

**Issue by JamesBremner** [JamesBremner/workshoplocator#3]
Currently, the application is using a test workshop mix.

https://github.com/JamesBremner/workshoplocator/blob/11adce11426708fa39092cab4927813f78403aee/src/main.cpp#L179-L196

You specified that the workshop mix should be defined at run time.  How do you want to do this?  

Suggestions:

- User prompt and input from terminal
- Read from text file

**Comment by ztlawton** [comment]
I was thinking along the lines of a user prompt or input at run time. Something like: I run the code, it asks for the Workshop mix as a string of 5 separate non-negative integers, I enter "5, 4, 3, 0, 0", and the code finds a layout for "5 Agriculture, 4 Biotech, 3 Electronics, 0 Energy, and 0 Heavy Industry".

**Comment by JamesBremner** [comment]
OK.

**Comment by JamesBremner** [comment]
This has changed from question to enhancement.

So please assign this.

**Comment by JamesBremner** [comment]
This issue has not moved in 3 hours.  I believe you are focussing on #2.

Would you like me to take this one over?

Here is a screenshot of what I would do:

![image](https://user-images.githubusercontent.com/2046227/232248306-5e4835f0-79f5-4089-9dc3-dff8be9e7aed.png)

**Comment by ztlawton** [comment]
Sorry, I forget that issues need to be closed.
